### ISSUE TITLE
Server is single-threaded

### ISSUE THREAD

**Issue by cberman** [cberman/web-challenges-server#2]
When multiple people are playing, the server is really slow. Please make it multi-threaded.

**Comment by nafod** [comment]
your wishes can and will be answered

**Comment by nafod** [comment]
Solved in ca1c6d06e48a851ee025b80fcf09b0ce50b5fa7c. You can install the required dependencies with `pip install -r requirements.txt` and then run it with either `foreman start (sqli/xss)` or just copy paste the commands from the Procfile. Also you need to set XSS_SECRET_KEY or SQLI_SECRET_KEY as env variables
